"""
LLM Service with provider abstraction.
Providers: GeminiProvider, OllamaProvider, MockProvider.
Selection driven by settings.LLM_PROVIDER env var.
"""
from __future__ import annotations

import logging
import textwrap
from abc import ABC, abstractmethod
from typing import Optional

import httpx
from fastapi import HTTPException

from app.core.config import settings

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Base
# ---------------------------------------------------------------------------

class LLMProvider(ABC):
    """Abstract base for all LLM providers."""

    @abstractmethod
    async def complete(self, prompt: str, *, system: str = "", max_tokens: int = 1024) -> str:
        """Return the model's text completion for the given prompt."""

    @property
    @abstractmethod
    def name(self) -> str:
        """Human-readable provider name."""


# ---------------------------------------------------------------------------
# MockProvider (default — no external calls, deterministic, used in tests)
# ---------------------------------------------------------------------------

class MockProvider(LLMProvider):
    """Deterministic mock for tests and development (no network required)."""

    name = "mock"

    async def complete(self, prompt: str, *, system: str = "", max_tokens: int = 1024) -> str:
        logger.debug("MockProvider.complete called (no real LLM)")
        excerpt = prompt[:120].replace("\n", " ")
        return (
            f"[MockLLM] Responding to: \"{excerpt}...\"\n\n"
            "This is a mock response generated by MockProvider. "
            "Configure LLM_PROVIDER=gemini or LLM_PROVIDER=ollama with the respective API key/URL "
            "in your .env file to enable real language model responses."
        )


# ---------------------------------------------------------------------------
# GeminiProvider
# ---------------------------------------------------------------------------

class GeminiProvider(LLMProvider):
    """Google Gemini via the google-generativeai SDK."""

    name = "gemini"

    def __init__(self) -> None:
        if not settings.GEMINI_API_KEY:
            raise HTTPException(
                status_code=502,
                detail={"error_code": "LLM_CONFIG_ERROR", "message": "GEMINI_API_KEY is not set in environment or backend/.env file."}
            )
        try:
            import google.generativeai as genai  # type: ignore
            genai.configure(api_key=settings.GEMINI_API_KEY)
            self._model = genai.GenerativeModel(settings.GEMINI_MODEL)
        except ImportError as exc:
            logger.error(f"google-generativeai package missing: {exc}")
            raise HTTPException(
                status_code=502,
                detail={"error_code": "LLM_DEPENDENCY_ERROR", "message": "google-generativeai package is not installed."}
            ) from exc

    async def complete(self, prompt: str, *, system: str = "", max_tokens: int = 1024) -> str:
        import asyncio
        import re
        import google.generativeai as genai  # type: ignore

        full_prompt = f"{system}\n\n{prompt}" if system else prompt
        loop = asyncio.get_running_loop()
        attempts = 3
        max_wait = 25

        for attempt in range(attempts):
            try:
                response = await loop.run_in_executor(
                    None,
                    lambda: self._model.generate_content(
                        full_prompt,
                        generation_config=genai.types.GenerationConfig(max_output_tokens=max_tokens),
                    ),
                )
                return response.text
            except Exception as exc:
                msg = str(exc)
                is_429 = (
                    "429" in msg
                    or "RESOURCE_EXHAUSTED" in msg
                    or "ResourceExhausted" in type(exc).__name__
                    or "quota" in msg.lower()
                )
                if is_429:
                    m = re.search(r"retry[^0-9]{0,30}(\d+)", msg, re.I)
                    wait = int(m.group(1)) + 1 if m else 2 ** (attempt + 1)
                    if attempt < attempts - 1 and wait <= max_wait and "PerDay" not in msg:
                        logger.warning(f"Gemini 429, retrying in {wait}s (attempt {attempt + 1}/{attempts})")
                        await asyncio.sleep(wait)
                        continue
                    logger.error(f"Gemini rate limit exhausted: {exc}")
                    _q = re.search(r'quota_id: "([^"]+)"', msg)
                    _qid = _q.group(1) if _q else None
                    raise HTTPException(
                        status_code=429,
                        detail={"error_code": "LLM_RATE_LIMITED", "message": "Gemini rate limit reached. Please retry shortly.", "retry_after": wait, "retry_after_seconds": wait, "quota_id": _qid},
                        headers={"Retry-After": str(wait)},
                    ) from exc
                logger.error(f"GeminiProvider API execution error: {exc}")
                raise HTTPException(
                    status_code=502,
                    detail={"error_code": "LLM_PROVIDER_ERROR", "message": f"Gemini API failure: {str(exc)}"},
                ) from exc


# ---------------------------------------------------------------------------
# OllamaProvider
# ---------------------------------------------------------------------------

class OllamaProvider(LLMProvider):
    """Ollama local inference server via HTTP."""

    name = "ollama"

    def __init__(self) -> None:
        self._base_url = settings.OLLAMA_BASE_URL.rstrip("/")
        self._model = settings.OLLAMA_MODEL

    async def complete(self, prompt: str, *, system: str = "", max_tokens: int = 1024) -> str:
        payload: dict = {
            "model": self._model,
            "prompt": prompt,
            "stream": False,
            "options": {"num_predict": max_tokens},
        }
        if system:
            payload["system"] = system

        try:
            async with httpx.AsyncClient(timeout=60.0) as client:
                resp = await client.post(f"{self._base_url}/api/generate", json=payload)
                resp.raise_for_status()
                data = resp.json()
                return data.get("response", "")
        except httpx.ConnectError as exc:
            logger.error(f"Ollama connection error: {exc}")
            raise HTTPException(
                status_code=502,
                detail={"error_code": "LLM_PROVIDER_OFFLINE", "message": f"Cannot connect to Ollama at {self._base_url}"}
            ) from exc
        except Exception as exc:
            logger.error(f"OllamaProvider error: {exc}")
            raise HTTPException(
                status_code=502,
                detail={"error_code": "LLM_PROVIDER_ERROR", "message": f"Ollama error: {str(exc)}"}
            ) from exc


# ---------------------------------------------------------------------------
# Factory / singleton
# ---------------------------------------------------------------------------

_provider_instance: Optional[LLMProvider] = None


def get_llm_provider() -> LLMProvider:
    """Return (and cache) the configured LLM provider singleton."""
    global _provider_instance
    if _provider_instance is None:
        provider_name = settings.LLM_PROVIDER.lower().strip()
        if provider_name == "gemini":
            _provider_instance = GeminiProvider()
        elif provider_name == "ollama":
            _provider_instance = OllamaProvider()
        else:
            if provider_name not in ("mock", ""):
                logger.warning(
                    f"Unknown LLM_PROVIDER='{provider_name}', falling back to MockProvider."
                )
            _provider_instance = MockProvider()
        logger.info(f"LLMService using provider: {_provider_instance.name}")
    return _provider_instance


class LLMService:
    """Thin wrapper around the configured LLM provider."""

    @staticmethod
    async def complete(
        prompt: str,
        *,
        system: str = "",
        max_tokens: int = 1024,
        provider: Optional[LLMProvider] = None,
    ) -> str:
        p = provider or get_llm_provider()
        return await p.complete(prompt, system=system, max_tokens=max_tokens)

    @staticmethod
    def build_rag_prompt(question: str, context_chunks: list[str]) -> str:
        """Format a standard RAG prompt from retrieved context chunks."""
        context = "\n\n---\n\n".join(context_chunks) if context_chunks else "No context retrieved."
        return textwrap.dedent(f"""
            You are an expert assistant for BIS (Bureau of Indian Standards) compliance and standards.
            Answer the following question strictly based on the provided context.
            If the context does not contain sufficient information, say so clearly — do NOT fabricate facts.

            CONTEXT:
            {context}

            QUESTION:
            {question}

            ANSWER:
        """).strip()

    @staticmethod
    def build_chat_prompt(
        question: str,
        context_chunks: list[str],
        history: list[dict],
        session_context: str = "",
        style: str = "simple",
    ) -> str:
        """Format a prompt for the chat endpoint including conversation history and style prompt."""
        history_text = ""
        if history:
            lines = []
            for h in history[-6:]:  # last 3 turns
                lines.append(f"User: {h.get('user', '')}")
                lines.append(f"Assistant: {h.get('assistant', '')}")
            history_text = "\n".join(lines)

        style_instruction = ""
        if style == "short":
            style_instruction = "Be concise and direct. Answer in 2-4 sentences maximum. Use plain language."
        elif style == "technical":
            style_instruction = "Provide a detailed technical response. Cite exact clause numbers, testing specs, and formal standards. Use structured sections where helpful."
        else:
            style_instruction = "Explain clearly in plain language. Be thorough but not verbose. Answer the question directly."

        context = "\n\n---\n\n".join(context_chunks) if context_chunks else ""
        ctx_section = f"\nSESSION CONTEXT:\n{session_context}\n" if session_context else ""
        rag_section = f"\nRELEVANT BIS DOCUMENTS:\n{context}\n" if context else ""
        hist_section = f"\nCONVERSATION HISTORY:\n{history_text}\n" if history_text else ""

        if context:
            grounding = (
                "Use the numbered documents above as your primary source. "
                "Cite them inline with [1], [2], etc. "
                "If a fact is not in the documents, say so clearly. "
                "Do NOT invent clause numbers or standard IDs."
            )
        else:
            grounding = (
                "No indexed BIS document matched this question. "
                "Answer from general knowledge and clearly state this is not verified against an indexed BIS document."
            )

        return textwrap.dedent(f"""
            You are a knowledgeable BIS (Bureau of Indian Standards) compliance assistant.
            {style_instruction}
            {grounding}

            Rules:
            - Answer the user's question directly. Do not start with a preamble.
            - Do not say "Certainly!" or "Great question!" or similar meta-commentary.
            - Do not use excessive headings for simple answers.
            - Do not repeat information already stated.
            - Do not fabricate standards, regulations, or compliance results.
            - Format bullet points and numbered lists for multi-step processes.
            - Keep the response focused and relevant.
            {ctx_section}{rag_section}{hist_section}
            USER QUESTION:
            {question}

            ANSWER:
        """).strip()
