"""
LLM Service with provider abstraction.
Providers: GeminiProvider, OllamaProvider, MockProvider.
Selection driven by settings.LLM_PROVIDER env var.
"""
from __future__ import annotations

import logging
import textwrap
from abc import ABC, abstractmethod
from typing import Optional

import httpx
from fastapi import HTTPException

from app.core.config import settings

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Base
# ---------------------------------------------------------------------------

class LLMProvider(ABC):
    """Abstract base for all LLM providers."""

    @abstractmethod
    async def complete(self, prompt: str, *, system: str = "", max_tokens: int = 1024) -> str:
        """Return the model's text completion for the given prompt."""

    @property
    @abstractmethod
    def name(self) -> str:
        """Human-readable provider name."""


# ---------------------------------------------------------------------------
# MockProvider (default — no external calls, deterministic, used in tests)
# ---------------------------------------------------------------------------

class MockProvider(LLMProvider):
    """Deterministic mock for tests and development (no network required)."""

    name = "mock"

    async def complete(self, prompt: str, *, system: str = "", max_tokens: int = 1024) -> str:
        logger.debug("MockProvider.complete called (no real LLM)")
        excerpt = prompt[:120].replace("\n", " ")
        return (
            f"[MockLLM] Responding to: \"{excerpt}...\"\n\n"
            "This is a mock response generated by MockProvider. "
            "Configure LLM_PROVIDER=gemini or LLM_PROVIDER=ollama with the respective API key/URL "
            "in your .env file to enable real language model responses."
        )


# ---------------------------------------------------------------------------
# GeminiProvider
# ---------------------------------------------------------------------------

class GeminiProvider(LLMProvider):
    """Google Gemini via the google-generativeai SDK."""

    name = "gemini"

    def __init__(self) -> None:
        if not settings.GEMINI_API_KEY:
            raise HTTPException(
                status_code=502,
                detail={"error_code": "LLM_CONFIG_ERROR", "message": "GEMINI_API_KEY is not set in environment or backend/.env file."}
            )
        try:
            import google.generativeai as genai  # type: ignore
            genai.configure(api_key=settings.GEMINI_API_KEY)
            self._model = genai.GenerativeModel(settings.GEMINI_MODEL)
        except ImportError as exc:
            logger.error(f"google-generativeai package missing: {exc}")
            raise HTTPException(
                status_code=502,
                detail={"error_code": "LLM_DEPENDENCY_ERROR", "message": "google-generativeai package is not installed."}
            ) from exc

    async def complete(self, prompt: str, *, system: str = "", max_tokens: int = 1024) -> str:
        import asyncio
        import google.generativeai as genai  # type: ignore

        full_prompt = f"{system}\n\n{prompt}" if system else prompt

        try:
            loop = asyncio.get_event_loop()
            response = await loop.run_in_executor(
                None,
                lambda: self._model.generate_content(
                    full_prompt,
                    generation_config=genai.types.GenerationConfig(max_output_tokens=max_tokens),
                ),
            )
            return response.text
        except Exception as exc:
            logger.error(f"GeminiProvider API execution error: {exc}")
            raise HTTPException(
                status_code=502,
                detail={"error_code": "LLM_PROVIDER_ERROR", "message": f"Gemini API failure: {str(exc)}"}
            ) from exc


# ---------------------------------------------------------------------------
# OllamaProvider
# ---------------------------------------------------------------------------

class OllamaProvider(LLMProvider):
    """Ollama local inference server via HTTP."""

    name = "ollama"

    def __init__(self) -> None:
        self._base_url = settings.OLLAMA_BASE_URL.rstrip("/")
        self._model = settings.OLLAMA_MODEL

    async def complete(self, prompt: str, *, system: str = "", max_tokens: int = 1024) -> str:
        payload: dict = {
            "model": self._model,
            "prompt": prompt,
            "stream": False,
            "options": {"num_predict": max_tokens},
        }
        if system:
            payload["system"] = system

        try:
            async with httpx.AsyncClient(timeout=60.0) as client:
                resp = await client.post(f"{self._base_url}/api/generate", json=payload)
                resp.raise_for_status()
                data = resp.json()
                return data.get("response", "")
        except httpx.ConnectError as exc:
            logger.error(f"Ollama connection error: {exc}")
            raise HTTPException(
                status_code=502,
                detail={"error_code": "LLM_PROVIDER_OFFLINE", "message": f"Cannot connect to Ollama at {self._base_url}"}
            ) from exc
        except Exception as exc:
            logger.error(f"OllamaProvider error: {exc}")
            raise HTTPException(
                status_code=502,
                detail={"error_code": "LLM_PROVIDER_ERROR", "message": f"Ollama error: {str(exc)}"}
            ) from exc


# ---------------------------------------------------------------------------
# Factory / singleton
# ---------------------------------------------------------------------------

_provider_instance: Optional[LLMProvider] = None


def get_llm_provider() -> LLMProvider:
    """Return (and cache) the configured LLM provider singleton."""
    global _provider_instance
    if _provider_instance is None:
        provider_name = settings.LLM_PROVIDER.lower().strip()
        if provider_name == "gemini":
            _provider_instance = GeminiProvider()
        elif provider_name == "ollama":
            _provider_instance = OllamaProvider()
        else:
            if provider_name not in ("mock", ""):
                logger.warning(
                    f"Unknown LLM_PROVIDER='{provider_name}', falling back to MockProvider."
                )
            _provider_instance = MockProvider()
        logger.info(f"LLMService using provider: {_provider_instance.name}")
    return _provider_instance


class LLMService:
    """Thin wrapper around the configured LLM provider."""

    @staticmethod
    async def complete(
        prompt: str,
        *,
        system: str = "",
        max_tokens: int = 1024,
        provider: Optional[LLMProvider] = None,
    ) -> str:
        p = provider or get_llm_provider()
        return await p.complete(prompt, system=system, max_tokens=max_tokens)

    @staticmethod
    def build_rag_prompt(question: str, context_chunks: list[str]) -> str:
        """Format a standard RAG prompt from retrieved context chunks."""
        context = "\n\n---\n\n".join(context_chunks) if context_chunks else "No context retrieved."
        return textwrap.dedent(f"""
            You are an expert assistant for BIS (Bureau of Indian Standards) compliance and standards.
            Answer the following question strictly based on the provided context.
            If the context does not contain sufficient information, say so clearly — do NOT fabricate facts.

            CONTEXT:
            {context}

            QUESTION:
            {question}

            ANSWER:
        """).strip()

    @staticmethod
    def build_chat_prompt(
        question: str,
        context_chunks: list[str],
        history: list[dict],
        session_context: str = "",
        style: str = "simple",
    ) -> str:
        """Format a prompt for the chat endpoint including conversation history and style prompt."""
        history_text = ""
        if history:
            lines = []
            for h in history[-6:]:  # last 3 turns
                lines.append(f"User: {h.get('user', '')}")
                lines.append(f"Assistant: {h.get('assistant', '')}")
            history_text = "\n".join(lines)

        style_instruction = ""
        if style == "short":
            style_instruction = "Give concise, direct, bulleted answers. Keep responses under 3-4 sentences."
        elif style == "technical":
            style_instruction = "Provide a deep technical and regulatory response citing exact clause numbers, testing specs, and formal standards."
        else:
            style_instruction = "Explain in plain, clear, accessible language easy to understand for non-experts."

        context = "\n\n---\n\n".join(context_chunks) if context_chunks else ""
        ctx_section = f"\nSESSION CONTEXT:\n{session_context}\n" if session_context else ""
        rag_section = f"\nRELEVANT STANDARDS/DOCUMENTS:\n{context}\n" if context else ""
        hist_section = f"\nCONVERSATION HISTORY:\n{history_text}\n" if history_text else ""
        grounding = (
            "Use the numbered documents below as your primary source and cite them inline like [1] or [2]. If something is not covered by them, say it comes from general knowledge and should be verified against the official standard. Never invent clause numbers."
            if context
            else "No indexed BIS document matched this question, so answer from general knowledge and state clearly that it is not verified against an indexed BIS document."
        )

        return textwrap.dedent(f"""
            You are a knowledgeable BIS Compliance & Standards Assistant.
            {style_instruction}
            You help users understand Indian standards, QCOs, certification requirements, and compliance.
            Do NOT fabricate standards, regulations, or compliance results.
            {grounding}
            {ctx_section}{rag_section}{hist_section}
            CURRENT QUESTION:
            {question}

            RESPONSE:
        """).strip()
